# Generated by Django 4.0.3 on 2022-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=1000)),
                ('task_deadline', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
