# Generated by Django 4.0.3 on 2022-04-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_user_alter_todo_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_completed']},
        ),
    ]
