# Generated by Django 4.0.3 on 2022-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
